### ISSUE TITLE
Can we universalize the Ubuntu/Debian packages and metapackages?

### ISSUE THREAD

**Issue by swelljoe** [virtualmin/virtualmin-lamp-stack-ubu#1]
How feasible would it be to do the same as https://github.com/virtualmin/virtualmin-install/issues/65 for Debian and Ubuntu?

The binaries are all identical already (just procmail-wrapper), but the groups are kinda different...but we're trying to consolidate. Can we cut down to just one repo and one set of lamp-stack packages for ubuntu/debian? Or maybe one for each of ubuntu and debian?

**Comment by swelljoe** [comment]
Note that it's possible to use logical or `|` in dependencies in a deb package, so if there are packages with different names, we can list them in the order we prefer them and it'll theoretically pull in the first one that is available...

**Comment by iliaross** [comment]
This is so awesome! I only had to drop `unrar` as it's not available on Debian. All the rest is working just fine.

Tested Debian 10-11 and Ubuntu 20.04-22.04!

**Comment by iliaross** [comment]
All is here - https://github.com/virtualmin/virtualmin-lamp-stack-ubu/commit/45a03798af23ce43f93ff1dfd2c2d11979303f3d#diff-e694ad373410d60c04daaa53a2c1334b6b1242f95dd14219023ea3e92ba31f01

**Comment by swelljoe** [comment]
You could make `unrar` a Recommends, perhaps?

**Comment by swelljoe** [comment]
Oh, it's already recommends. That should not prevent installation. Only `Depends` are hard dependencies that will prevent installation, even if Recommends are being attempted. I think. Needs testing of course.

Some asshole is going to immediately use this to install on some non-LTS version and immediately ask us 8 million questions.

We need to make sure the installer makes it obvious that installing on anything other than a grade A supported OS is a terrible idea and we will not try to help solve problems on unsupported OSes.

**Comment by iliaross** [comment]
> Some asshole is going to immediately use this to install on some non-LTS version and immediately ask us 8 million questions.

:-)

> We need to make sure the installer makes it obvious that installing on anything other than a grade A supported OS is a terrible idea 

It's already hidden. Or you want more words in `-h` output?

> Oh, it's already recommends. That should not prevent installation. Only Depends are hard dependencies that will prevent installation, even if Recommends are being attempted. I think. Needs testing of course.

No reason to add it as `unrar` already installed on Ubuntu and missing on Debian.

**Comment by swelljoe** [comment]
I dunno why we didn't do this sooner (I do...used to be a lot more packages and a lot more difference between distros). I can suddenly remove dozens of repositories from my list of pains in my ass, and rolling new distro versions is going to be mostly just testing and making sure Virtualmin-Config handles any config file location changes or whatever...

**Comment by iliaross** [comment]
I think you had to do it, as things got easier and more unified just over the past years.

**Comment by iliaross** [comment]
But this is awesome to have one file per type.

**Comment by iliaross** [comment]
I think we can either create a new repo or rename this one and delete `virtualmin-lamp-stack-deb`.

**Comment by swelljoe** [comment]
We haven't done a Virtualmin 7 release yet, so we can refactor right here. No need to do anything to accommodate backward compatibility here.

**Comment by iliaross** [comment]
Yeah, I wasn't even referring to backward compatibility. As this is now universal repo for Ubuntu/Debian systems it's perhaps better to call it `virtualmin-lamp-stack`.

We must make sure that we create a bunch of links for Virtualmin 6 installs to stay on upgrades. Also, make sure we won't upgrade a stack package on Ubuntus for current Virtualmin 6 installs.

**Comment by swelljoe** [comment]
Ah, right! I didn't even follow that. I guess we could. We can mark deb repo deprecated, link here, and I'll rename this one, maybe.

**Comment by swelljoe** [comment]
> We must make sure that we create a bunch of links for Virtualmin 6 installs to stay on upgrades.

I have no idea what you mean? Virtualmin 6 repos are staying exactly where they are. No links.

**Comment by iliaross** [comment]
> I have no idea what you mean? Virtualmin 6 repos are staying exactly where they are. No links.

Oh, I see. But will you push updates there as well?

**Comment by swelljoe** [comment]
The universal repos aren't changing how they work. They've always been...universal.

I don't expect to need to push any updates to the binary repos or lamp/lemp stack packages for Virtualmin 6. (And, the only thing now in the binary repos is procmail-wrapper, right?)

**Comment by iliaross** [comment]
On Ubuntu/Debian - yes. On RHEL it's also `jailkit` package.

**Comment by swelljoe** [comment]
Well, it continues to be the case that Virtualmin 6 has its own repos that will not change.

I am unlikely to roll any updates to the binary repos, but if I do, it'll be the same as it always was.

**Comment by swelljoe** [comment]
This is one of several reasons every major release gets a new repo base directory. We can make changes to literally anything about the installation or repositories, without actually breaking anything for anyone. (Some Virtualmin 7 beta installations will break, though. They'll just have to deal with it. I warned them.).

**Comment by iliaross** [comment]
> They'll just have to deal with it. I warned them.)

Alright. It will be easily fixable with `install.sh -s` command.

> I am unlikely to roll any updates to the binary repos, but if I do, it'll be the same as it always was.

What do you mean?

**Comment by swelljoe** [comment]
I mean jailkit and procmail-wrapper do not change often. If I need to roll an update, it will be exactly the same process as before, because Virtualmin 6 repos are completely separate from the Virtualmin 7 repos.

**Comment by iliaross** [comment]
If you can make it work on Fedora then it would be smooth.
